version: '3'
services:
  pgdb:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_MAX_CONNECTIONS: 200
    ports:
      - "5432:5432"
  quarkus-blocking:
    build:
      context: ../../..
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: quarkus-blocking
    restart: always
    ports:
      - "8080:8080"
#    depends_on:
#      - pgdb
    volumes:
      - /Users/bhavesh.shah/work/projects/brevitaz-internal/sample.txt:/deployments/sample.txt
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres-db:5432/mydatabase
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
networks:
  java-research:
    driver: bridge
